# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CacheBeta@0
  inputs:
    key: npm | $(Agent.OS) | package-lock.json
    path: $(npm_config_cache)
  displayName: Cache npm

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'npm install'

- task: DownloadSecureFile@1
  displayName: 'Download couchdb local.ini file'
  name: localini
  inputs:
    secureFile: 'couchdb_local.ini'    

- task: PowerShell@2
  displayName: 'Copy couchdb local.ini to $HOME/couchdb/local.d'
  inputs:
    targetType: 'inline'
    script: |
      New-Item -Type Directory -Force "${HOME}/couchdb/local.d"
      Copy-Item -Force "$(localini.secureFilePath)" "${HOME}/couchdb/local.d/local.ini"    

- task: DockerInstaller@0
  displayName: Install Docker
  inputs:
    dockerVersion: 17.09.0-ce
    releaseType: stable
    
- script: |
    docker run -e COUCHDB_USER=admin -e COUCHDB_PASSWORD=admin -p 5984:5984 --name couchdb -v ${HOME}/couchdb/local.d -d couchdb
  displayName: 'run couchdb Docker image'

- script: |
    ng test --karmaConfig karma.conf.ci.js
  displayName: 'perform unit tests'    

- script: |
    ng build --prod
  displayName: 'build koia with "ng build --prod"'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'koiadist'
    targetPath: 'dist/koia'
