trigger:
- master

variables:
  npm_config_cache: $(Pipeline.Workspace)/.npm

pool:
  vmImage: 'ubuntu-latest'

steps:

# install Node.js and npm packages
- task: CacheBeta@0
  inputs:
    key: npm | $(Agent.OS) | package-lock.json
    path: $(npm_config_cache)
  displayName: Cache npm packages

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm ci -g @angular/cli
    npm ci
  displayName: 'Install npm packages'

# set-up and rund CouchDB in Docker container (used by unit tests)
- task: DownloadSecureFile@1
  displayName: 'Download couchdb local.ini file'
  name: couchdb_local_ini
  inputs:
    secureFile: 'couchdb_local.ini'    

- task: PowerShell@2
  displayName: 'Copy couchdb local.ini to $HOME/couchdb/etc/local.d'
  inputs:
    targetType: 'inline'
    script: |
      New-Item -Type Directory -Force "${HOME}/couchdb/etc/local.d"
      Copy-Item -Force "$(couchdb_local_ini.secureFilePath)" "${HOME}/couchdb/etc/local.d/local.ini"    

- task: DockerInstaller@0
  displayName: Install Docker
  inputs:
    dockerVersion: 17.09.0-ce
    releaseType: stable
    
- script: |
    docker run -p 5984:5984 --name couchdb -v ${HOME}/couchdb/etc/local.d:/opt/couchdb/etc/local.d -d couchdb
  displayName: 'run CouchDb in Docker container'

# perform and publish unit-tets
- script: |
    npx ng test --watch=false --karmaConfig karma.conf.ci.js
  displayName: 'perform unit tests'    

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TESTS-*.xml'
  displayName: 'publish unit test results'

# build product and publish artifact
- script: |
    npx ng build --prod
  displayName: 'build koia product'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'koiadist'
    targetPath: 'dist/koia'
  displayName: 'publish artifact'